version: '3'

services:
  server:
    container_name: ecommerce-server
    image: nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./docker/server/site.conf:/etc/nginx/conf.d/default.conf
      - ./server:/srv
    depends_on:
      - php-server

  php-server:
    container_name: ecommerce-php-server
    build: ./docker/server
    restart: on-failure
    volumes:
      - ./server:/srv

  db:
    container_name: ecommerce-db
    build: ./docker/db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Ho_Chi_Minh'
    volumes:
      - database:/var/lib/mysql
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: ecommerce-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=ecommerce-db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8080:80

  composer:
    container_name: ecommerce-composer
    image: composer
    command: 'composer install -o'
    volumes:
      - ./server:/srv
    working_dir: /srv

volumes:
  database:
